from .base import BaseRepository
from .user import UserRepository
from .student import StudentRepository
from .teacher import TeacherRepository
from .discipline import DisciplineRepository
from .period import PeriodRepository
from .class_ import ClassRepository
from .enrollment import EnrollmentRepository
from .assessment import AssessmentRepository
from .grade import GradeRepository
