from .user import UserService
from .student import StudentService
from .teacher import TeacherService
from .discipline import DisciplineService
from .period import PeriodService
from .class_ import ClassService
from .enrollment import EnrollmentService
from .assessment import AssessmentService
from .grade import GradeService
from .report import ReportService
